In [ ]:
%pip install playwright
!python -m playwright install chromium

Downloading Chrome for Testing 149.0.7827.55 (playwright chromium v1228) from https://cdn.playwright.dev/builds/cft/149.0.7827.55/win64/chrome-win64.zip
|                                                                                |   0% of 183.6 MiB
|■■■■■■■■                                                                        |  10% of 183.6 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 183.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 183.6 MiB
Chrome for Testing 149.0.7827.55 (playwright chromium v1228) downloaded to C:\Users\Solange\AppData\Local\ms-playwright\chromium-1228
Downloading Chrome Headless Shell 149.0.7827.55 (playwright chromium-headless-shell v1228) from https://cdn.playwright.dev/builds/cft/149.0.7827.55/win64/chrome-headless-shell-win64.zip
|                                                                                |   0% of 113.6 MiB
|■■■■■■■■                                                                        |  10% of 113.6 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 113.6 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 113.6 MiB
Chrome Headless Shell 149.0.7827.55 (playwright chromium-headless-shell v1228) downloaded to C:\Users\Solange\AppData\Local\ms-playwright\chromium_headless_shell-1228

In [1]:
import asyncio
from maps_scraper import scraper

query = input("Type your google maps query: ")

data = await scraper(query)

========== CARD 1 ==========
Name:
Lanchão Do NaldoLanchão Do Naldo  4,4Restaurante · Rua Piratininga na, R. Prof.
Cleaned Data: {'card_url': 'https://www.google.com/maps/place/Lanch%C3%A3o+Do+Naldo/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07668c94b799:0x58b502d71a547fa5!8m2!3d-23.6042838!4d-46.9257569!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyeG9XR0pyZUc5Wk1YQlVVbFZXYkZnd2NIaFNhMUpEVjI1Q1RWcEdSUkFC4AEA-gEECAAQKA!16s%2Fg%2F11gfk6yw7z?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WF+7M', 'place_name': 'Lanch%C3%A3o Do Naldo', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}
Results: [{'card_url': 'https://www.google.com/maps/place/Lanch%C3%A3o+Do+Naldo/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07668c94b799:0x58b502d71a547fa5!8m2!3d-23.6042838!4d-46.9257569!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyeG9XR0pyZUc5Wk1YQlVVbFZXYkZnd2NIaFNhMUpEVjI1Q1RWcEdSUkFC4AEA-gEECAAQKA!16s%2Fg%2F11gfk6yw7z?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WF+7M', 'place_name': 'Lanch%C3%A3o Do Naldo', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}]
Link: https://www.google.com/maps/place/Lanch%C3%A3o+Do+Naldo/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07668c94b799:0x58b502d71a547fa5!8m2!3d-23.6042838!4d-46.9257569!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyeG9XR0pyZUc5Wk1YQlVVbFZXYkZnd2NIaFNhMUpEVjI1Q1RWcEdSUkFC4AEA-gEECAAQKA!16s%2Fg%2F11gfk6yw7z?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D
Plus Code: 93WF+7M Centro, Cotia - SP

========== CARD 2 ==========
Name:
Restaurante TauáRestaurante Tauá  4,2Restaurante ·  · R. Sen. Feijó, 267Cozinha
Cleaned Data: {'card_url': 'https://www.google.com/maps/place/Restaurante+Tau%C3%A1/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07650d2ba16b:0xd0924c8cd4a35d6d!8m2!3d-23.6046009!4d-46.9284056!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOV2JEaGhiMkozRUFF4AEA-gEECAAQRA!16s%2Fg%2F1s04h9q7f?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WC+5J', 'place_name': 'Restaurante Tau%C3%A1', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}
Results: [{'card_url': 'https://www.google.com/maps/place/Lanch%C3%A3o+Do+Naldo/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07668c94b799:0x58b502d71a547fa5!8m2!3d-23.6042838!4d-46.9257569!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyeG9XR0pyZUc5Wk1YQlVVbFZXYkZnd2NIaFNhMUpEVjI1Q1RWcEdSUkFC4AEA-gEECAAQKA!16s%2Fg%2F11gfk6yw7z?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WF+7M', 'place_name': 'Lanch%C3%A3o Do Naldo', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}, {'card_url': 'https://www.google.com/maps/place/Restaurante+Tau%C3%A1/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07650d2ba16b:0xd0924c8cd4a35d6d!8m2!3d-23.6046009!4d-46.9284056!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOV2JEaGhiMkozRUFF4AEA-gEECAAQRA!16s%2Fg%2F1s04h9q7f?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WC+5J', 'place_name': 'Restaurante Tau%C3%A1', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}]
Link: https://www.google.com/maps/place/Restaurante+Tau%C3%A1/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07650d2ba16b:0xd0924c8cd4a35d6d!8m2!3d-23.6046009!4d-46.9284056!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOV2JEaGhiMkozRUFF4AEA-gEECAAQRA!16s%2Fg%2F1s04h9q7f?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D
Plus Code: 93WC+5J Centro, Cotia - SP

========== CARD 3 ==========
Name:
Restaurante LavouraRestaurante Lavoura  4,9Restaurante brasileiro ·  · R. Dez d
Cleaned Data: {'card_url': 'https://www.google.com/maps/place/Restaurante+Lavoura/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf0780692d27c3:0xfb23e6505aa5525a!8m2!3d-23.6028951!4d-46.9318181!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEUYnJhemlsaWFuX3Jlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUnliamh0TXpsM1JSQULgAQD6AQQIABA5!16s%2Fg%2F11vf6h4tqb?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93W9+R7', 'place_name': 'Restaurante Lavoura', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}
Results: [{'card_url': 'https://www.google.com/maps/place/Lanch%C3%A3o+Do+Naldo/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07668c94b799:0x58b502d71a547fa5!8m2!3d-23.6042838!4d-46.9257569!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyeG9XR0pyZUc5Wk1YQlVVbFZXYkZnd2NIaFNhMUpEVjI1Q1RWcEdSUkFC4AEA-gEECAAQKA!16s%2Fg%2F11gfk6yw7z?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WF+7M', 'place_name': 'Lanch%C3%A3o Do Naldo', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}, {'card_url': 'https://www.google.com/maps/place/Restaurante+Tau%C3%A1/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf07650d2ba16b:0xd0924c8cd4a35d6d!8m2!3d-23.6046009!4d-46.9284056!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOV2JEaGhiMkozRUFF4AEA-gEECAAQRA!16s%2Fg%2F1s04h9q7f?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93WC+5J', 'place_name': 'Restaurante Tau%C3%A1', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}, {'card_url': 'https://www.google.com/maps/place/Restaurante+Lavoura/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf0780692d27c3:0xfb23e6505aa5525a!8m2!3d-23.6028951!4d-46.9318181!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEUYnJhemlsaWFuX3Jlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUnliamh0TXpsM1JSQULgAQD6AQQIABA5!16s%2Fg%2F11vf6h4tqb?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D', 'plus_code': '93W9+R7', 'place_name': 'Restaurante Lavoura', 'Latitude': '-23.6042838', 'Longitude': '-46.9978547', 'neighborhood': '\uf186 Centro', 'city': 'Cotia', 'state': 'SP'}]
Link: https://www.google.com/maps/place/Restaurante+Lavoura/@-23.6042838,-46.9978547,13z/data=!4m11!1m3!2m2!1srestaurantes+em+cotia!6e5!3m6!1s0x94cf0780692d27c3:0xfb23e6505aa5525a!8m2!3d-23.6028951!4d-46.9318181!15sChVyZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEUYnJhemlsaWFuX3Jlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUnliamh0TXpsM1JSQULgAQD6AQQIABA5!16s%2Fg%2F11vf6h4tqb?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D
Plus Code: 93W9+R7 Centro, Cotia - SP

In [2]:
import pandas as pd

df = pd.DataFrame(data)
display(df)

,card_url,plus_code,place_name,Latitude,Longitude,neighborhood,city,state
0,https://www.google.com/maps/place/Lanch%C3%A3o...,93WF+7M,Lanch%C3%A3o Do Naldo,-23.6042838,-46.9978547, Centro,Cotia,SP
1,https://www.google.com/maps/place/Restaurante+...,93WC+5J,Restaurante Tau%C3%A1,-23.6042838,-46.9978547, Centro,Cotia,SP
2,https://www.google.com/maps/place/Restaurante+...,93W9+R7,Restaurante Lavoura,-23.6042838,-46.9978547, Centro,Cotia,SP

In [ ]:

df.to_excel(query + ".xlsx", index=False)

Empty DataFrame
Columns: [card_url, plus_code, place_name, Latitude, Longitude, neighborhood, city, state]
Index: []

In [14]:
import pandas as pd
def cleaning(link: str, plus_code: str) -> dict:

    # Using the link to extract the place name and coordinates (latitude and longitude)

    link_data = link.removeprefix("https://www.google.com/maps/place/")

    place_name = link_data.split("/")[0]\
        .replace("+", " ")\
        .replace("-", " ")

    coordinates = link_data.split("/")[1]\
        .split(",")

    Latitude, Longitude = coordinates[0].replace("@", ""), coordinates[1]

    # Cleaning the Plus Code by removing any unwanted characters

    pcode = plus_code.split(" ")[0]

    pcode = pcode.replace("", "")

    location = plus_code.replace(pcode, "")\
        .strip()

    # Extracting neighborhood, city, and state from the location string

    neighborhood = location.split(",")[0]\
        .strip()

    city = location.split(",")[1]\
        .split(" - ")[0]\
        .strip()

    state = location[-2:].strip()

    return {
        "card_url": link,
        "plus_code": pcode,
        "place_name": place_name,
        "Latitude": Latitude,
        "Longitude": Longitude,
        "neighborhood": neighborhood,
        "city": city,
        "state": state
    }

In [ ]:
teste = 'Restaurante LavouraRestaurante Lavoura  4,9Restaurante brasileiro ·  · R. Dez'
import re

name = re.search(r'^(.*?)\s{2,}', teste).group(1)
len_name = len(name)
print(name[:len_name//2])  # Output: Restaurante Lavoura

rate = re.search(r'(\d+,\d+)', teste).group(1)
print(rate)  # Output: 4,9

Restaurante Lavoura
4,9

In [3]:
plus_code = "8Q7X+G9 Cotia - SP, Brazil"
link = "https://www.google.com/maps/place/Restaurante+Tau%C3%A1/@-23.6046009,-47.0005034,13z/data=!4m11!1m3!2m2!1sRestaurantes+em+cotia!6e5!3m6!1s0x94cf07650d2ba16b:0xd0924c8cd4a35d6d!8m2!3d-23.6046009!4d-46.9284056!15sChVSZXN0YXVyYW50ZXMgZW0gY290aWFaFyIVcmVzdGF1cmFudGVzIGVtIGNvdGlhkgEKcmVzdGF1cmFudJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOV2JEaGhiMkozRUFF4AEA-gEECAAQRA!16s%2Fg%2F1s04h9q7f?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D"

import re

match = re.search(r'!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)', link)

if match:
    latitude = match.group(1)
    longitude = match.group(2)

print(latitude, longitude)

-23.6046009 -46.9284056